source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'BackgroundUpload-CocoaLumberjack' do
  pod "BackgroundUpload-CocoaLumberjack", :path => "../"
  pod "CocoaLumberjack"
  
  target 'Tests' do
     inherit! :search_paths 
  end  
end


